# ░█████╗░███████╗██████╗░░█████╗░████████╗██╗░█████╗░███╗░░██╗░██████╗░██████╗████████╗░█████╗░░█████╗░██╗░░██╗███████╗██████╗░
# ██╔══██╗██╔════╝██╔══██╗██╔══██╗╚══██╔══╝██║██╔══██╗████╗░██║██╔════╝██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██║░██╔╝██╔════╝██╔══██╗
# ███████║█████╗░░██████╔╝██║░░██║░░░██║░░░██║██║░░██║██╔██╗██║╚█████╗░╚█████╗░░░░██║░░░███████║██║░░╚═╝█████═╝░█████╗░░██████╔╝
# ██╔══██║██╔══╝░░██╔═══╝░██║░░██║░░░██║░░░██║██║░░██║██║╚████║░╚═══██╗░╚═══██╗░░░██║░░░██╔══██║██║░░██╗██╔═██╗░██╔══╝░░██╔══██╗
# ██║░░██║██║░░░░░██║░░░░░╚█████╔╝░░░██║░░░██║╚█████╔╝██║░╚███║██████╔╝██████╔╝░░░██║░░░██║░░██║╚█████╔╝██║░╚██╗███████╗██║░░██║
# ╚═╝░░╚═╝╚═╝░░░░░╚═╝░░░░░░╚════╝░░░░╚═╝░░░╚═╝░╚════╝░╚═╝░░╚══╝╚═════╝░╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝░╚════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝
# Автор плагина: anton_flame (ТГК: https://t.me/anton_flame_coder)

# Настройки плагина
settings:
  # Настройка лимитов стаканья зелий
  limits:
    # Максимальное количество стакнутых обычных зелий
    default_potion: 32
    # Максимальное количество стакнутых взрывных зелий
    splash_potion: 16
    # Максимальное количество стакнутых туманных зелий
    lingering_potion: 8

    # Настройка лимитов стаканья зелий для групп LuckPerms
    luckperms:
      enabled: true
      default:
        # Максимальное количество стакнутых обычных зелий
        default_potion: 32
        # Максимальное количество стакнутых взрывных зелий
        splash_potion: 16
        # Максимальное количество стакнутых туманных зелий
        lingering_potion: 8
      hero:
        # Максимальное количество стакнутых обычных зелий
        default_potion: 36
        # Максимальное количество стакнутых взрывных зелий
        splash_potion: 20
        # Максимальное количество стакнутых туманных зелий
        lingering_potion: 12
      titan:
        # Максимальное количество стакнутых обычных зелий
        default_potion: 40
        # Максимальное количество стакнутых взрывных зелий
        splash_potion: 24
        # Максимальное количество стакнутых туманных зелий
        lingering_potion: 16

# Сообщения плагина
messages:
  # Сообщение при недостатке прав
  no-permission: "&cУ Вас недостаточно прав!"
  # Сообщение при перезагрузке конфигурации
  reloaded: "&fКонфигурация была перезагружена!"
  # Хелп-сообщение
  help:
    - ""
    - "&fПомощь по плагину &6AFPotionsStacker&f:"
    - "&6/afpotionsstacker reload &f- перезагрузить конфигурацию"
    - ""