name: AFPotionsStacker
version: '${project.version}'
main: ru.anton_flame.afpotionsstacker.AFPotionsStacker
api-version: '1.16'
authors: [anton_flame]
softdepend: [LuckPerms, Vault, LuckPerms]
commands:
  afpotionsstacker:
    aliases:
      - afps